name: CMake

on:
  push:
    branches:
      - main
      - fix/**
      - feat/**
  pull_request:
    branches: 
      - main

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Configure CMake
        run: |
          cmake --version
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Update template-generated files
        run: |
          git diff --quiet ||
          {
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config user.name "github-actions[bot]"
            git add .
            git status
            git commit -m "chore: update CMake-configured files"
            git push
          }

#      - name: Test
#        working-directory: ${{github.workspace}}/build
#        run: ctest -C ${{env.BUILD_TYPE}}
